name: Merge Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./people
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Build the directory
        run: ./directory.sh