name: Merge Pull Request

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  on_pr:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build and Commit
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          docker run -e PAT=${{ secrets.PAT }} ghcr.io/nmagee/ds2002-directory:v1
          # docker run -v ${{ github.workspace }}:/app -e PAT=${{ secrets.PAT }} ghcr.io/nmagee/ds2002-directory:v1
          git add .
          git commit -m "Update directory listing [skip ci]" || echo "No changes to commit"
          git push
