name: Merge Pull Request

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  on_pr:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Git Pull
        run: |
          git pull origin main
      - name: Build and Commit
        run: |
          ./docker/directory.sh
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update directory listing [skip ci]" || echo "No changes to commit"
          git push origin main
