name: Merge Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./people
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4  
      - name: Build directory
        run: ./directory.sh
      - name: Add-Commit-Push
        run: |
          git config user.name "Neal Magee"
          git config user.email "nem2p@virginia.edu"
          git add .
          git commit -m "Adding new student listing"
          git push