name: Merge Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    permissions:
      contents: write
      issues: write
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./people
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - run: |
          ./directory.sh
          git config user.name "Neal Magee"
          git config user.email "nem2p@virginia.edu"
          git add -A
          git commit -m "Adding new student listing"
          git push