name: Merge Pull Request

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  issues: write

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./people
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Update listings
        run: ./directory.sh
      - name: Commit back
        run: |
          git config user.name "Neal Magee"
          git config user.email "nem2p@virginia.edu"
          git commit -am "Adding new student listing"
          git push