name: Merge Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  on_pr:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Build and Commit
        run: |
          docker run -e PAT=${{ secrets.PAT }} ghcr.io/nmagee/ds2002-directory:v1
